// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCb-S7VwWreaBZNakH_x898XYtJCD21I',
    appId: '1:630548431873:android:95ba5c9863738fc538ec00',
    messagingSenderId: '630548431873',
    projectId: 'dphe-imvs',
    storageBucket: 'dphe-imvs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JNBCugzfaCFMSk085j3lIfeE1W1QbOs',
    appId: '1:630548431873:ios:e727000bb9a3c54938ec00',
    messagingSenderId: '630548431873',
    projectId: 'dphe-imvs',
    storageBucket: 'dphe-imvs.appspot.com',
    iosBundleId: 'com.example.dphe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-JNBCugzfaCFMSk085j3lIfeE1W1QbOs',
    appId: '1:630548431873:ios:86ce483333a32d2838ec00',
    messagingSenderId: '630548431873',
    projectId: 'dphe-imvs',
    storageBucket: 'dphe-imvs.appspot.com',
    iosBundleId: 'com.example.dphe.RunnerTests',
  );
}
